version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: secret_board
      TZ: "Asia/Tokyo"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:
    external: true
    name: secret-board-db
